name: Main App Test and Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-main-app:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run tests with coverage
      run: npm run test:ci
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: main-app
        name: main-app-coverage
        
    - name: Build production
      run: npm run build
      
  cross-repo-integration:
    runs-on: ubuntu-latest
    needs: test-main-app
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - run: npm ci
    
    # Install latest CLI for integration testing
    - name: Install supabase-lite CLI
      run: npm install -g supabase-lite@latest
    
    # Test integration capabilities
    - name: Test cross-repository integration
      run: |
        echo "Cross-repository integration tests would run here"
        echo "This could test CLI compatibility, API endpoints, etc."